### ISSUE TITLE
Specific request in relation to prevent close of browser itself

### ISSUE THREAD

**Issue by Dwarden** [Christoph142/DownloadControl#5]
Hi,

i noticed in your extension this:

> Ask for confirmation before closing the browser while there are downloads in progress

would be possible to make simple-yet-effective fork from this into separate extension?
one which would allow prevent closing of the chrome / opera (29.x) browser 

i'm looking for quite some time for simple extension with just "prevent close" and/or 'minimize-to-tray"

i think it would be quite popular if you could make it and publish

thanks in advance and keep up your great work

**Comment by Christoph142** [comment]
It's possible, but AFAIK this doesn't work in latest versions of Opera anymore. They changed the shutdown behavior and dialogs now won't prevent it from shutting down anymore. So the only ones who can fix this are Opera's devs I'm afraid.

**Comment by Dwarden** [comment]
thanks for the confirmation, so it's same problem as Chrome 
(aka the issue isn't by Opera devs but Chromium)
... so much  for innovation ... leading to just more frustration to user
